### ISSUE TITLE
[Media] No pagination in media list view

### ISSUE THREAD

**Issue by dannyvw** [Kunstmaan/KunstmaanBundlesCMS#1900]
In the thumb view you have pagination but not in the list view

**Comment by Numkil** [comment]
Hey @dannyvw 
This has been fixed recently. I think it was done in this PR #1627. This might not yet be deployed on the demo website.

The pagination threshold for the list view is 25 objects per page.
I will close the issue but if you have any other problems please do not hesitate to reopen the issue.

**Comment by dannyvw** [comment]
@Numkil  We updated to version 5.0.5 and the issue still exists. In which version is this fixed?

**Comment by Numkil** [comment]
I use 5.0.x-dev because the fix has not been included in the next 5 release. 
however you other issue about the

**Comment by dannyvw** [comment]
@Numkil Thanks for the information
