### ISSUE TITLE
Admin language changes on using the language picker for content.

### ISSUE THREAD

**Issue by Numkil** [Kunstmaan/KunstmaanBundlesCMS#2691]
I noticed in a few versions of the bundles that  when you change the language of the content you want to edit the whole UI changes language with it instead of using the language chosen in your user object. This is a regression i think.

**Comment by acrobat** [comment]
Fixed by #2692

**Comment by krewetka** [comment]
I still have this problem in 5.6.2 somehow despite I have changes from #2692

**Comment by Numkil** [comment]
hi @krewetka could you share us a screenshot of the issue happening? that would help us a long way in figuring out where it still goes wrong. Also please take notice that the media folder tab is intentionally translated in the language of the content. we could discuss wether this is  something we want to keep doing but that was how the CMS was built back in the day.

**Comment by krewetka** [comment]
@Numkil  I described a bit more here https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1873 when it comes to internals ( priorities of listeners etc).

Screenshot of issues are:

- before fixing it by changing priorities myself:

![image](https://user-images.githubusercontent.com/207319/88572115-f084b480-d03e-11ea-8f19-ba18bd9eabd8.png)

![image](https://user-images.githubusercontent.com/207319/88572129-f8dcef80-d03e-11ea-92e9-8393b0a9be5e.png)

- after fixing it it behaves like this

![image](https://user-images.githubusercontent.com/207319/88572201-114d0a00-d03f-11ea-8587-8b709a779cda.png)

I try to migrate application from 4.2 to newest version and before it it was for me working like on the last sreenshot.

**Comment by krewetka** [comment]
@Numkil  did you have chance to check this problem?

I made temporary fix in my code with overriding event subscriber and changed priority but still would be good to figure it out.

Do anyone have idea why AdminLocaleListener has comment:

` // Must be registered before the default Locale listener`? :thinking: 

For me it works only when it is registered after and not before.

**Comment by krewetka** [comment]
@acrobat I can confirm that in my case it was problem with `kunstmaan_admin.default_locale: ar` instead of setting fallback locale there which is `en`.

It was not clear in docs what this is for and how it is used and difference between this and `default_admin_locale`.

My incorrect assumption was that it is website default locale which is "ar" and not "copy" of symfony framework default locale :)
