### ISSUE TITLE
Dependencies Missing, unable to install Bundles.

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#975]
I have just checked out a new copy of the bundles using

composer create-project kunstmaan/bundles-standard-edition

There are now several errors the first has been addresses here: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2048 and can be fixed

The second appears to be specific to Kunstmaan and is a fatal error:

```bash
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                       
  The service "ekino.new_relic.request_listener" has a dependency on a non-existent service "kunstmaan_newrelic_naming_strategy".
```

This second error also happens on any installs that I do a composer update on today. I can see which packages have been updated but neither of the ones referred to by the error have updated. Here is the output from a composer update from a bundles install I have that went from working to broken:

```bash
  - Removing twig/twig (v1.23.3)
  - Installing twig/twig (v1.24.0)
    Loading from cache

  - Removing paragonie/random_compat (1.1.5)
  - Installing paragonie/random_compat (1.1.6)
    Loading from cache

  - Removing knplabs/knp-gaufrette-bundle (0.2.0)
  - Installing knplabs/knp-gaufrette-bundle (0.3.0)
    Loading from cache

  - Removing gedmo/doctrine-extensions (v2.4.10)
  - Installing gedmo/doctrine-extensions (v2.4.12)
    Loading from cache

  - Removing stof/doctrine-extensions-bundle (v1.2.1)
  - Installing stof/doctrine-extensions-bundle (v1.2.2)
    Loading from cache

  - Removing symfony/swiftmailer-bundle (v2.3.9)
  - Installing symfony/swiftmailer-bundle (v2.3.11)
    Loading from cache

  - Installing zendframework/zend-eventmanager (3.0.0)
    Loading from cache

  - Installing zendframework/zend-code (2.6.2)
    Loading from cache

  - Installing ocramius/proxy-manager (1.0.2)
    Loading from cache

  - Removing doctrine/migrations (v1.2.2)
  - Installing doctrine/migrations (v1.3.0)
    Loading from cache

  - Removing behat/mink-browserkit-driver (v1.3.0)
  - Installing behat/mink-browserkit-driver (v1.3.1)
    Loading from cache

  - Removing phpunit/phpunit (4.8.21)
  - Installing phpunit/phpunit (4.8.22)
    Loading from cache

  - Removing doctrine/doctrine-cache-bundle (1.2.2)
  - Installing doctrine/doctrine-cache-bundle (1.3.0)
    Loading from cache

  - Removing friendsofsymfony/http-cache (1.4.1)
  - Installing friendsofsymfony/http-cache (1.4.2)
    Loading from cache

  - Removing guzzlehttp/psr7 (1.2.1)
  - Installing guzzlehttp/psr7 (1.2.2)
    Loading from cache

  - Updating friendsofsymfony/user-bundle dev-master (6ccff96 => 8f1fc22)
    Checking out 8f1fc2273b37c61ddcc1620abf4500320a23763e
```

This is running on PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)

Thanks

**Comment by iknowfoobar** [comment]
Currently removing ekino/newrelic-bundle fixes this for me. I don't use it so not a problem

**Comment by iknowfoobar** [comment]
Unfortunately remove ekino/newrelic-bundle doesn't fix this. It just leads to another similar error:

```bash
PHP Fatal error:  Uncaught exception 'Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException' with message 'The service "monolog.handler.nested" has a dependency on a non-existent service "kunstmaan_logging_formatter".'
```

What has changed that is causing these problems?

**Comment by sandergo90** [comment]
Hi,

Were you creating a new project or did you execute the create-project command on an existing project ?

We have tried to do the same a few minutes ago and did not find the fatal error. Maybe try to delete the entire folder and create a new project.

**Comment by kimausloos** [comment]
@iknowfoobar in your config_prod.yml there is probably still a reference to 'kunstmaan_logging_formatter' in the nested monolog handler. If you remove that it should be ok. But new projects should install without errors, like @sandergo90 said, so feel free to comment if you're setting up a new project.

**Comment by iknowfoobar** [comment]
It started because I got the error when creating a new project using the create-project command. Then to see if it was affecting other projects I ran composer updates on them too and they all showed the same symptoms.

**Comment by kimausloos** [comment]
@iknowfoobar could you try creating a new project maybe? We pushed release 3.4.1 a couple of hours ago to fix the FOSUserBundleIssue, so that one should work now. I also tried doing a new project with flag dev, that one works too.

**Comment by iknowfoobar** [comment]
It appears that creating a new project is fine now. However all my current projects are still broken? 
Removing 'kunstmaan_logging_formatter' from config_prod.yml has no effect. The problem happens in all environments and I can't see that reference in any other config files.

I am going to have to roll back any composer updates to these projects and update them one at a time to see which one is causing the problem

**Comment by iknowfoobar** [comment]
Moment of madness!!! Sorry guys I had put a fix for the fos user bundle in the config, forgotten that there were more services in the the same file and overwritten them! 

Thanks for the help anyway.
